[package]
name = "gaem"
version = "0.1.0"
authors = ["fourtf <tf.four@gmail.com>"]
build = "build.rs"

[build-dependencies]
gl_generator = "0.5.0"

[dependencies]
# gfx-hal = "0.3.0"
sdl2 = "0.32.2"
# gl = "0.13.0"